---
engines:
  eslint:
    enabled: true
    channel: eslint-4
    checks:
      import/no-unresolved:
        enabled: false
ratings:
  paths:
  - "*.js"
exclude_paths:
- .tmp_rules/**/*
- node_modules/**/*
- test/**/*
