---
engines:
  eslint:
    enabled: true
    channel: eslint-3
    checks:
      import/no-unresolved:
        enabled: false
  stylelint:
    enabled: true
    channel: "beta"
ratings:
  paths:
  - "**.js"
exclude_paths:
- node_modules/**/*
- test/**/*
